# Generated by Django 2.1.5 on 2019-01-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
    ]
