# Generated by Django 2.1.5 on 2019-01-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='DateAdded',
            field=models.BigIntegerField(null=True),
        ),
    ]
