# Generated by Django 2.1.5 on 2019-01-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190120_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='Event',
        ),
    ]
