# Generated by Django 2.1.5 on 2019-01-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190122_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='SourceURL',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
