# Generated by Django 2.1.5 on 2019-01-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190123_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='DataMapCountry',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
