# Generated by Django 2.1.5 on 2019-01-24 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_datamapcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
